AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool
  HelloWorldAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuth:
            UserPoolArn:
              Fn::GetAtt:
              - UserPool
              - Arn
            Identity:
              Header: Authorization
  HelloWorldFunctionAuthorized:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://rhynos-testing-stuff/832ffc9c1c78829ad8b6c070298985cf
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: HelloWorldAPI
            Path: /hello
            Method: get
            Auth:
              Authorizer: MyCognitoAuth
  HelloWorldFunctionNoAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://rhynos-testing-stuff/832ffc9c1c78829ad8b6c070298985cf
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: HelloWorldAPI
            Path: /hello-no-auth
            Method: get
  PostFunctionTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://rhynos-testing-stuff/832ffc9c1c78829ad8b6c070298985cf
      Handler: add_to_table.lambdaHandler
      Runtime: nodejs8.10
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Environment:
        Variables:
          TABLE_NAME: test
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: HelloWorldAPI
            Path: /hello
            Method: post
  TestTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: test
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${HelloWorldAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
